name: Ansible Molecule

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "22.04"
          # - image: "enterpriselinux"
          #   tag: "8"
          # - image: "enterpriselinux"
          #   tag: "latest"
          # - image: "debian"
          #   tag: "latest"
          # - image: "debian"
          #   tag: "bullseye"
          # - image: "fedora"
          #   tag: "38"
          # - image: "fedora"
          #   tag: "latest"
          # - image: "fedora"
          #   tag: "rawhide"
          # - image: "opensuse"
          #   tag: "latest"
          # - image: "ubuntu"
          #   tag: "bionic"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
